language: node_js
node_js:
- '10'

sudo: false
dist: trusty

addons:
  chrome: stable
  code_climate:
    repo_token:
      secure: "Qg05d4W5BfhbxXy9E9M8ACo2ULSs6tGL5We3pTCAH+smnCKKjXv5Bl+Tu7fC6Cup15LchVUGOxJ/RqXRWV3YEnwqYYZohj0EZANKedLfI8efFXlY1aIs6g29DbWzoCVbG8EczcNY7thakYzW37xkua3GdywH2s7l384bjCOsVDw="

cache:
  yarn: true

install:
  - yarn install --ignore-engines

jobs:
  include:
    - stage: test
      script:
        - yarn build
        - yarn test:ci
      after_script:
        - codeclimate-test-reporter < coverage/lcov.info
    - stage: npm release
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function npm_dist_tag() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo "next"
          else
            echo "latest"
          fi
        }
      deploy:
        provider: npm
        tag: $(npm_dist_tag)
        email: rwwagner90@gmail.com
        skip_cleanup: true
        api_key:
          secure: "qmXLSbGcujfLg8h+cJFjJtrEBeWGqd1CdhOex3TOCz93BrJUQf7he66HCBJaJ178qEYTnw4WKjjlcfbYO29H88Z+jnrS5KJydmRg0D3rkPSxcD8TMK3d8vRUTDl+UubuqPnN8jG4IqGfpM1z7WPSN1WSTjFK648S261bK7w88JY="
        on:
          branch: master
          tags: true
          repo: shipshapecode/shepherd
        after_deploy: |
          if [ "$(npm_dist_tag)" == "latest" ]; then
            npm dist-tag rm shepherd.js next || true
          fi
    - stage: gh-pages release
      script:
        - yarn build
      before_deploy:
        - git add -f --all dist/
      deploy:
        provider: pages
        skip-cleanup: true
        github-token:
          secure: "mEepiSPDRKYAC4tTk/jXqDQOGRvVi4tdcONlU8U/TCWd3ZYg8BStKO8mQlPSVE7kVo2HTscgo256jvt1ee47P0K0Oawe7eyOvH8E+bYt0bu/LqpbtwfkX95a4MiVWc717kU/AX6lKAU3Ggnhdkw4AII8ZDFr9NLMGiL4bVokki8="
        keep-history: true
        on:
          branch: master
